# Generated by Django 5.2.7 on 2025-11-04 09:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_administrador_cliente_corredortributario_sistema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='alerta',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerta',
            name='usuario_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentotributario',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos_tributarios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xls', 'xlsx'])]),
        ),
        migrations.AddField(
            model_name='documentotributario',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentotributario',
            name='usuario_subida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documentotributario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documentotributario',
            name='tipo',
            field=models.CharField(blank=True, default='Documento Cliente', max_length=45),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
