# Generated by Django 5.2.7 on 2025-11-04 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_alerta_options_alerta_leido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateField()),
                ('secuencia_evento', models.BigIntegerField()),
                ('valor_historico', models.DecimalField(decimal_places=8, default=0.0, max_digits=18)),
                ('año', models.IntegerField(blank=True, null=True)),
                ('instrumento', models.CharField(blank=True, max_length=50)),
                ('factor', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='api.sistema')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
