# Generated by Django 5.2.7 on 2025-11-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_calificaciontributaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
